# This is a basic workflow to help you get started with Actions

name: CI Backend

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: issue_tracking_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        working-directory: backend
        run: dotnet restore

      - name: Build the API
        working-directory: backend
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        working-directory: backend
        run: dotnet test --no-build --verbosity normal
